### ISSUE TITLE
Bug in Node Expansion during AStar search?

### ISSUE THREAD

**Issue by DigitalEd** [luxkun/ReGoap#21]
In ReGoapNode.cs, there seems to be a bug on line 149 in the Expand method.
The line:
`!goal.HasAnyConflict(precond)` seems to be an error.

Any action that has a precondition that's different than the goal will always be rejected. Consider the case where the goal GoSwimming requires { isAtPosition: 0} and a JumpIntoWater action with effect {isAtPosition: 0} and a precondition {isAtPosition: 1}. 
The action precondition will always be in conflict (as it should be) with the goal and therefore never be chosen for the expandList.

Bug? Or am I misunderstanding something?

----- Ed

**Comment by luxkun** [comment]
Not working a lot on this project right now, but you are right, let me know if this branch fixes your issue:
https://github.com/luxkun/ReGoap/tree/conflicting-actions

**Comment by DigitalEd** [comment]
That seems to fix it
