### ISSUE TITLE
Compiler error after import to unity

### ISSUE THREAD

**Issue by dimmduh** [luxkun/ReGoap#29]
2017.4.1f1

> The type or namespace name `CompilerErrorCollection' does not exist in the namespace `System.CodeDom.Compiler'. Are you missing an assembly reference?

**Comment by dimmduh** [comment]
Fixed by changing Player settings -> Api Compatibility level -> NET 2.0

**Comment by Tokenyet** [comment]
2018.3.4f1 here,
Not working, NET 2.0 is my default value. I have no idea to slove this :(

**Comment by Tokenyet** [comment]
Never mind, I change It to 4.0 and It works 😩

**Comment by zaddo67** [comment]
This is probably worth mentioning in the instructions because if you just create the Unity project using default settings and load ReGoap, you get this error.  

I am on Unity 6.  Changed to IL2CPP .NET Framework, All good now.
